---

domain: devoxx

logstash_forwarder_cert: files/certs/logstash-forwarder.pem
logstash_forwarder_key: files/certs/logstash-forwarder.key
logstash_lumberjack_host: kibana.{{ domain }}
logstash_lumberjack_port: 5043

# graphite configuration
graphite_host: graphite.{{ domain }}
grafana_host: grafana.{{ domain }}
elasticsearch_host: elasticsearch.{{ domain }}
rundeck_host: rundeck.{{ domain }}

# nexus configuration
nexus_url: http://nexus.{{ domain }}:8081/nexus

# seyren configuration
seyren_graphite_url: "http://{{ graphite_host }}"
seyren_port: 8080
seyren_url: "http://{{ graphite_host }}:{{ seyren_port }}"
