---

ec2_image: ami-bf1e688f
ec2_region: us-west-2 
ec2_instance_type: t1.micro
ec2_security_group: permit_all

logstash_forwarder_cert: "files/certs/logstash-forwarder.pem"
logstash_forwarder_key: "files/certs/logstash-forwarder.key"
logstash_lumberjack_host: "{{ groups['loggers'][0] }}"
logstash_lumberjack_port: "5043"

graphite_url: http://graphite.warsjawa.uservices.pl/ 
grafana_elasticsearch_url: http://{{ groups['loggers'][0] }}:9200

grafana_server_name: grafana.warsjawa.uservices.pl
