---

logstash_forwarder_cert: "files/certs/logstash-forwarder.pem"
logstash_forwarder_key: "files/certs/logstash-forwarder.key"
logstash_lumberjack_host: "{{ groups['loggers'][0] }}"
logstash_lumberjack_port: "5043"

graphite_url: http://{{ groups['graphite'][0] }}/ 
grafana_elasticsearch_url: http://{{ groups['loggers'][0] }}:9200
