---
hostname: localhost
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_plugins:
  - git
  - sonar
  - ssh
  - gradle
  - greenballs
  - rundeck
  - delivery-pipeline-plugin
  - build-pipeline-plugin
  - job-dsl
  - nested-view
  - parameterized-trigger
  - compact-columns
  - extra-columns
  - thinBackup
  - timestamper
  - jobConfigHistory
  - ghprb
  - stash-pullrequest-builder
  - stashNotifier
  - plain-credentials
