---

- name: add elasticsearch apt key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch  state=present

- name: add elasticsearch apt repository
  apt_repository: >
    repo='deb http://packages.elasticsearch.org/logstashforwarder/debian stable main'
    state=present
    update_cache=yes

- name: install logstash-forwarder
  apt: name=logstash-forwarder state=present


- name: ensure logstash-forwarder has its SSL certificate
  copy: src=files/certs/logstash-forwarder.pem dest=/etc/ssl/certs/logstash-forwarder.pem owner=root group=root mode=0755

- name: ensure logstash-forwarder has its SSL private key
  copy: src=files/certs/logstash-forwarder.key dest=/etc/ssl/private/logstash-forwarder.key owner=root group=root mode=0755

- name: ensure logstash-forwarder has its config file
  template: src=config.json.j2 dest=/etc/logstash-forwarder owner=root group=root mode=0755
  notify:
    - restart logstash-forwarder
