---
- name: Create an user to host Grafana
  user: name={{ grafana_owner }}

- name: download grafana
  get_url: dest={{ grafana_graphite_root }}/grafana-{{ grafana_version }}.tar.gz url=http://grafanarel.s3.amazonaws.com/grafana-{{ grafana_version }}.tar.gz

- name: extract grafana tarball
  shell: >
    tar -zxvf {{ grafana_graphite_root}}/grafana-{{ grafana_version }}.tar.gz -C {{ grafana_graphite_root}}
    creates={{ grafana_graphite_root}}/grafana-{{ grafana_version }}
  notify:
    - set permissions

- name: link grafana version
  file: >
    path={{ grafana_graphite_root }}/dist
    src={{ grafana_graphite_root }}/grafana-{{ grafana_version }}
    state=link 
