---
- name: Create VHost file
  template: src=grafana_vhost.conf.j2 dest="{{ apache_vhost_dest }}/grafana.conf" owner={{ grafana_owner }}
  notify:
  - Restart Apache

- name: Link grafana.conf to sites enabled
  command: ln -sf {{ apache_vhost_dest }}/grafana.conf {{ apache_vhost_enabled }}/
