---

- name: install apache packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - apache2-mpm-worker
  notify:
    - enable apache

- name: enable modules
  command: a2enmod {{ item }}
  register: a2enmod
  changed_when: a2enmod.stdout.startswith('To activate the new configuration')
  with_items: apache_modules
  notify:
    - restart apache
