---

- name: install apache packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - apache2-mpm-worker
    - libapache2-mod-wsgi
  notify:
    - enable apache

- name: enable headers module
  command: a2enmod headers
  register: a2enmod
  changed_when: a2enmod.stdout.startswith('To activate the new configuration')
  notify:
    - restart apache
