---

- name: Lookup OS specific variables
  include_vars: "Debian.yml"
  tags: debian

- name: Install apache packages for Debian
  apt: "name={{ item }} state=present update_cache=yes"
  with_items: apache_pkgs

- name: Create symlink for headers
  command: ln -sf /etc/apache2/mods-available/headers.load /etc/apache2/mods-enabled/headers.load