---
- name: sshd
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for sshd to be running
      local_action: "wait_for host={{ inventory_hostname }} delay=0 port={{ ansible_ssh_port }} timeout=90 state=started"
        
- name: Server for logging applications
  hosts: loggers
  sudo: yes

  vars_files:
   - vars/loggers.yml

  roles:
    - { role: redis, tags: ["loggers", "loggers-redis"] }
    - { role: elasticsearch, tags: ["loggers", "loggers-elasticsearch"] }
    - { role: logstash, tags: ["loggers", "loggers-logstash"] }
    - { role: nginx-kibana, tags: ["loggers", "loggers-nginx-kibana"] }

- name: Server for applications
  hosts: apps
  sudo: yes

  vars_files:
   - vars/apps.yml
   - vars/loggers.yml

  roles:
    - { role: jdk8, tags: ["apps", "apps-jdk8"] }
    - { role: zookeeper, tags: ["apps", "apps-zookeeper"] }
    - { role: logstash-forwarder, tags: ["apps", "apps-logstash-forwarder"] }

- name: Server for metrics
  hosts: graphite
  user: '{{ ssh_user }}'
  sudo: true
  gather_facts: yes
  vars:
    ssh_user: root
  roles:
    - { role: apache, tags: ["graphite", "graphite-apache"] }
    - { role: graphite, tags: ["graphite", "graphite-core"] }
    - { role: grafana, tags: ["graphite", "graphite-grafana"] }
    - { role: elasticsearch-graphite, tags: ["graphite", "graphite-elasticsearch"] }
    
- name: Server for nexus
  hosts: nexus
  user: '{{ ssh_user }}'
  sudo: true
  gather_facts: no
    
  vars_files:
   - vars/nexus.yml
   
  roles:
    - { role: sonatype-nexus, tags: ["nexus"] }
