---
- hosts: loggers
  sudo: yes

  vars_files:
   - vars/default.yml

  roles:
    - { role: redis, tags: ["redis"] }
    - { role: elasticsearch, tags: ["elasticsearch"] }
    - { role: logstash, tags: ["logstash"] }
    - { role: nginx-kibana, tags: ["nginx-kibana"] }
    - { role: logstash-forwarder, tags: ["logstash-forwarder"] }
