---

- name: setup github repositories
  hosts: jenkins
  pre_tasks:
    - include_vars: "hackathons/default.yml"
    - include_vars: "hackathons/{{ hackathon_edition }}.yml"
  roles:
    - { 
        role: jenkins_job,
        jenkins_job_projects: "{{ projects }}",
        jenkins_job_github_organization: "{{ github_organization }}",
      }
