---

- name: download logstash-forwarder package
  get_url:
    url: "{{ logstash_forwarder_package_url }}"
    dest: "/tmp/{{ logstash_forwarder_package }}"

- name: install logstash-forwarder
  apt:
    deb: "/tmp/{{ logstash_forwarder_package }}"

- name: ensure logstash-forwarder has its SSL certificate
  copy: src=files/certs/logstash-forwarder.pem dest=/etc/ssl/certs/logstash-forwarder.pem owner=root group=root mode=0755

- name: ensure logstash-forwarder has its SSL private key
  copy: src=files/certs/logstash-forwarder.key dest=/etc/ssl/private/logstash-forwarder.key owner=root group=root mode=0755

- name: ensure logstash-forwarder has its config file
  template: src=config.json.j2 dest=/etc/logstash-forwarder owner=root group=root mode=0755
  notify:
    - restart logstash-forwarder
