---

- name: enable elasticsearch repository
  apt_repository:
    repo: "deb http://packages.elasticsearch.org/elasticsearch/{{ elasticsearch_version }}/debian stable main"
    state: present

- name: add elasticsearch repo key
  apt_key:
    url: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

- name: install required packages
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
   - openjdk-7-jre
   - elasticsearch

- name: enable CORS (required by Kibana 3)
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "{{ item }}"
    state: present
  with_items:
    - 'http.cors.enabled: true'
    - 'http.cors.allow-origin: "/.*/"'
  notify:
    - restart elasticsearch 

- name: start and enable elasticsearch service
  service:
    name: elasticsearch
    state: started
    enabled: yes
