---

- name: enable Elasticsearch repository
  apt_repository: >
    repo="deb http://packages.elasticsearch.org/elasticsearch/{{ elasticsearch_version }}/debian stable main"
    state=present

- name: add Elasticsearch repo key
  apt_key: url="http://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present

- name: install required packages
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
   - openjdk-7-jre
   - elasticsearch

- name: start and enable Elasticsearch service
  service: name=elasticsearch state=started enabled=yes
