---

- name: Restart Apache
  service: name=apache2 state=restarted

- name: set permissions
  file: >
    path={{ grafana_graphite_root }}/grafana-{{ grafana_version }}
    owner={{ grafana_owner }}
    group={{ grafana_owner }}
    state=directory

