---
  - name: Create "nexus" group
    group: name=nexus

  - name: Create "nexus" user
    user: name=nexus group=nexus groups="sudo"

  - include: openjdk.yml

  - include: download.yml

  - include: configure.yml

  - include: startup.yml

  - include: nginx.yml
